# Generated by Django 3.1.7 on 2021-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranotherconfig',
            name='startDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='useranotherconfig',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
    ]
