# Generated by Django 3.1.7 on 2021-03-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('endTime', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('title', models.CharField(max_length=128, verbose_name='作者名')),
                ('desc', models.CharField(default='暂无简介信息', max_length=256, verbose_name='简介')),
            ],
            options={
                'verbose_name': '作者信息表',
                'verbose_name_plural': '作者信息表',
                'ordering': ['-createTime', '-endTime'],
            },
        ),
    ]
