# Generated by Django 3.1.7 on 2021-03-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovelApp', '0002_auto_20210306_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者信息表', 'verbose_name_plural': '作者信息表'},
        ),
    ]
