# Generated by Django 3.1.7 on 2021-03-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelApp', '0004_auto_20210306_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('endTime', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='小说类型名')),
            ],
            options={
                'verbose_name': '小说类型表',
                'verbose_name_plural': '小说类型表',
                'ordering': ['-createTime', '-endTime'],
            },
        ),
    ]
