# Generated by Django 3.1.7 on 2021-03-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelApp', '0009_auto_20210306_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=128, verbose_name='章节标题'),
        ),
    ]
